#!/usr/bin/env ruby
# encoding: utf-8

def parse_line(line)
  c = 0
  while line[c]=='*'
    c += 1
  end
  return c, line[(c+1)..-1]
end

line_no = false
label = ARGV[0] || ""
if label.index('*,') == 0
  line_no = true
  label = label.slice(2,label.length-2)
end

lines = $stdin.readlines.collect {|l| l.force_encoding("utf-8")}
$stdout.write "\\begin{algt}\n"
$stdout.write "\\label{#{label}}\n" if label != ""
title = lines.shift.strip
if title != "*"
  $stdout.write "\\noindent {\\bf #{title}}\\\\\n"
else
  $stdout.write "\\noindent "
end
n = 1
lines.each do |line|
  $stdout.write "\\\\\n" if n != 1
  if line_no
    lnum = "#{n}."
    $stdout.write lnum
    $stdout.write "\\settowidth{\\algbackindent}{#{lnum}}"
    $stdout.write "\\hspace*{-\\algbackindent}"
  end
  n += 1

  indent, rest = parse_line(line.chomp)
  indent_str = "\\hspace*{0.2in}" * indent
  $stdout.write "#{indent_str} #{rest}"
end
$stdout.write "\n"
$stdout.write "\\end{algt}\n"
