#!/usr/bin/env ruby
# encoding: utf-8

require 'open3'

MACRO_START = '---'
BASE_PATH = File.dirname(__FILE__)

class String
  def macro_starts?
    self.start_with? MACRO_START
  end
end

def extract_macro_name(line)
  res = /^---(\w+)(|\[(.*)\])(|\s+(.*))$/.match line
  name = res[1]
  options = res[3] || ''
  rest = (res[5] || '') + "\n"
  return name,options,rest
end

def call_macro(name,options,data)
  script_name = File.join(BASE_PATH,'macros',name)
  if File.exists? script_name
    cmd = "#{script_name} #{options}"
    Open3.popen2(script_name) do |i,o,w|
      data.each do |d|
        i.write d
      end
      i.close
      return o.readlines
    end
  end
  return []
end

def process_macro(lines)
  name,options,rest = extract_macro_name lines[0]
  if rest.chomp != ''
    data = [rest] + lines[1..-1]
  else
    data = lines[1..-1]
  end
  call_macro(name,options,data)
end

def main
  input_filename, output_filename = ARGV[0..1]

  fin = open(input_filename,"r:utf-8")
  lines = fin.readlines
  output = []
  lcount = lines.length

  i = 0
  while i<lcount
    line = lines[i]

    if line.macro_starts?
      j = i+1
      while j<lcount and (!lines[j].macro_starts?)
        j+=1
      end

      last = j-1
      output += process_macro(lines[i..last])

      i = last + 2
      next
    end

    output << lines[i]
    i += 1
  end

  open(output_filename,"w") do |fout|
    output.each do |line|
      fout.write line
    end
  end
end

main

